### ISSUE TITLE
Missing directory when installing action

### ISSUE THREAD

**Issue by yoogx** [ada-actions/toolchain#7]
Hi,

Thanks for the action, it is exactly what I needed.

Yet, I experienced recently a crash with the ada-action on my 3 builds (Linux, macOS, Windows)
See https://github.com/OpenAADL/ocarina/runs/1401540078?check_suite_focus=true for details
Note this action built properly before

It looks like a recent update may have created the issue below, and that something is missing from ada-actions/toolchain. Any idea what is going on?

What surprises me is that I thought my configuration file would lock to a release of the action itself, and not point on to the tip of this repository.

2020-11-15T03:05:24.0311877Z Cache Size: ~916 MB (960324203 B)
2020-11-15T03:05:24.0448587Z [command]/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/3ef5bf14-ac7d-41c9-8bdf-e4e163984b06/cache.tzst -P -C /home/runner/work/ocarina/ocarina
2020-11-15T03:06:10.9870123Z Cache restored from key: Linux-gnat-ce-2020
2020-11-15T03:06:11.0188267Z ##[group]Run ada-actions/toolchain@ce2020
2020-11-15T03:06:11.0188610Z with:
2020-11-15T03:06:11.0188866Z   distrib: community
2020-11-15T03:06:11.0189144Z   target: native
2020-11-15T03:06:11.0189411Z   community_year: 2020
2020-11-15T03:06:11.0189703Z   install_dir: ./cached_gnat
2020-11-15T03:06:11.0189981Z ##[endgroup]
2020-11-15T03:06:11.0566607Z internal/modules/cjs/loader.js:800
2020-11-15T03:06:11.0567002Z     throw err;
2020-11-15T03:06:11.0567364Z     ^
2020-11-15T03:06:11.0567834Z 
2020-11-15T03:06:11.0568733Z Error: Cannot find module './utils'
2020-11-15T03:06:11.0569714Z Require stack:
2020-11-15T03:06:11.0570617Z - /home/runner/work/_actions/ada-actions/toolchain/ce2020/node_modules/@actions/core/lib/command.js
2020-11-15T03:06:11.0576639Z - /home/runner/work/_actions/ada-actions/toolchain/ce2020/node_modules/@actions/core/lib/core.js
2020-11-15T03:06:11.0592191Z - /home/runner/work/_actions/ada-actions/toolchain/ce2020/lib/main.js
2020-11-15T03:06:11.0593971Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
2020-11-15T03:06:11.0594925Z     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
2020-11-15T03:06:11.0595513Z     at Module.require (internal/modules/cjs/loader.js:852:19)
2020-11-15T03:06:11.0596026Z     at require (internal/modules/cjs/helpers.js:74:18)
2020-11-15T03:06:11.0597437Z     at Object.<anonymous> (/home/runner/work/_actions/ada-actions/toolchain/ce2020/node_modules/@actions/core/lib/command.js:11:17)
2020-11-15T03:06:11.0598164Z     at Module._compile (internal/modules/cjs/loader.js:959:30)
2020-11-15T03:06:11.0598979Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2020-11-15T03:06:11.0599603Z     at Module.load (internal/modules/cjs/loader.js:815:32)
2020-11-15T03:06:11.0600181Z     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
2020-11-15T03:06:11.0600783Z     at Module.require (internal/modules/cjs/loader.js:852:19) {
2020-11-15T03:06:11.0601411Z   code: 'MODULE_NOT_FOUND',
2020-11-15T03:06:11.0601743Z   requireStack: [
2020-11-15T03:06:11.0602534Z     '/home/runner/work/_actions/ada-actions/toolchain/ce2020/node_modules/@actions/core/lib/command.js',
2020-11-15T03:06:11.0603539Z     '/home/runner/work/_actions/ada-actions/toolchain/ce2020/node_modules/@actions/core/lib/core.js',
2020-11-15T03:06:11.0604421Z     '/home/runner/work/_actions/ada-actions/toolchain/ce2020/lib/main.js'
2020-11-15T03:06:11.0604828Z   ]

**Comment by yoogx** [comment]
Looks like this issue has been solved in my last run. Is it an issue you have corrected in your last series of patches? This is not obvious for me
